import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Search Visibility Scorecard: Growth Marketing Demo",
  description:
    "Portfolio demo: a measurement framework for brand visibility in AI answer engines (ChatGPT, Gemini, Perplexity), built around Adobe products with simulated data.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Nav />
        <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8">{children}</main>
        <footer className="border-t border-border-subtle bg-white">
          <div className="mx-auto max-w-6xl space-y-2 px-4 py-6 text-xs text-muted">
            <p>
              Independent portfolio project by Philip Felix. Not affiliated with or endorsed by Adobe. Adobe, Adobe
              Express, Firefly, Acrobat, Photoshop, and Premiere Pro are trademarks of Adobe Inc.; other product names
              are trademarks of their respective owners and are used here only to illustrate a measurement framework.
            </p>
            <p>
              Every metric shown is simulated demo data generated by a seeded script. No real answer-engine sampling, no
              Adobe internal data. Industry reference points are cited to their public sources on the Methodology page.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
